version: '3.5'
services:
  auth-service-redis-dev:
    container_name: auth-service-redis-dev
    image: redis:6.2.6-alpine
    restart: on-failure
    command:
      - 'redis-server'
      - '--port ${AUTH_REDIS_PORT}'
      - '--requirepass ${AUTH_REDIS_PASSWORD}'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--databases 1'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--maxmemory ${REDIS_MAXMEM:-50mb}'
      - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
    volumes:
      - 'volume-auth-service-redis-dev:/data/redis'
    ports:
      - ${AUTH_REDIS_EXTERNAL_PORT}:${AUTH_REDIS_PORT}
    networks:
      - external-network

networks:
  external-network:
    driver: bridge
    
volumes:
  volume-auth-service-redis-dev: