version: '3.5'
services:
  auth-service-postgres-dev:
    image: postgres:12.1
    container_name: auth-service-postgres-dev
    restart: on-failure
    ports:
      - ${AUTH_DB_EXTERNAL_PORT}:${AUTH_DB_PORT}
    environment:
      - POSTGRES_USER=${AUTH_DB_USER}
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}
      - POSTGRES_DB=${AUTH_DB_NAME}
      - POSTGRES_HOST=${AUTH_DB_HOST}
    volumes:
      - ../../aspnet-microservices-volumes/volume-auth-service-postgres-dev:/var/lib/postgresql/data

  auth-service-redis-dev:
    container_name: auth-service-redis-dev
    image: redis:6.2.6-alpine
    restart: on-failure
    command:
      - 'redis-server'
      - '--port ${AUTH_REDIS_PORT}'
      - '--requirepass ${AUTH_REDIS_PASSWORD}'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--databases 1'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--maxmemory ${REDIS_MAXMEM:-50mb}'
      - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
    volumes:
      - '../../aspnet-microservices-volumes/volume-auth-service-redis-dev:/data/redis'
    ports:
      - ${AUTH_REDIS_EXTERNAL_PORT}:${AUTH_REDIS_PORT}
    networks:
      - external-network

networks:
  external-network:
    driver: bridge
    
# volumes:
#   volume-auth-service-postgres-dev:
#   volume-auth-service-redis-dev: